name: module_s1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2 # Lưu ý: Hãy đảm bảo Flutter SDK của bạn đã nâng cấp lên bản mới nhất để hỗ trợ Dart 3.9

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_svg: ^2.0.10
  audioplayers: ^6.1.0 
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AvaterSoftware_001.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  # Khai báo assets phải lùi vào 4 khoảng trống (2 tab) so với lề trái
  assets:
    - lib/database/script/create_tables.sql
    - lib/database/script/create_indexes.sql
    - lib/database/script/create_triggers.sql
    - lib/database/script/seed_data.sql

    - assets/images/
    #- assets/snound_effect



